# Catalogue Service Endpoint 
# Voting App Syncs the Origami List from Catalogue Service 
# at an interval of 1 min 
catalogue.service-url=http://catalogue.app.svc.cluster.local:5000/api/products

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# application.properties
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

